use super::dynamic_band::{BandMode, BandSettings, FilterKind};
use serde::{Deserialize, Serialize};

pub const MAX_EQ_BANDS: usize = 5;

#[derive(Clone, Copy, Debug)]
pub struct EqPreset {
    pub name: &'static str,
    pub bands: [BandSettings; MAX_EQ_BANDS],
    pub default_mix: f32,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EqPresetKind {
    Broadcast,
    BroadcastSoft,
    OpenOffice,
    ConferenceHall,
    GeneralVoice,
    Podcast,
    Meeting,
}

impl EqPresetKind {
    pub const fn all() -> [Self; 7] {
        [
            Self::Broadcast,
            Self::BroadcastSoft,
            Self::OpenOffice,
            Self::ConferenceHall,
            Self::GeneralVoice,
            Self::Podcast,
            Self::Meeting,
        ]
    }

    pub const fn preset(self) -> &'static EqPreset {
        match self {
            EqPresetKind::Broadcast => &BROADCAST,
            EqPresetKind::BroadcastSoft => &BROADCAST_SOFT,
            EqPresetKind::OpenOffice => &OPEN_OFFICE,
            EqPresetKind::ConferenceHall => &CONFERENCE_HALL,
            EqPresetKind::GeneralVoice => &GENERAL_VOICE,
            EqPresetKind::Podcast => &PODCAST,
            EqPresetKind::Meeting => &MEETING,
        }
    }

    pub fn default_mix(self) -> f32 {
        self.preset().default_mix
    }

    pub fn display_name(self) -> &'static str {
        self.preset().name
    }

    pub fn description(self) -> &'static str {
        match self {
            EqPresetKind::Broadcast => "播音级预设：厚实、温暖、通透，饱满低频与空气感。",
            EqPresetKind::BroadcastSoft => "播音级（柔和）：降低高频与瞬态锐度，更耐听。",
            EqPresetKind::OpenOffice => "开放办公：强力去浑浊与穿透力，抑制环境人声。",
            EqPresetKind::ConferenceHall => "会议室去混响：削驻波，补空气感，模拟近讲干声。",
            EqPresetKind::GeneralVoice => "平衡的参数，适合大多数场景",
            EqPresetKind::Podcast => "更强齿音控制，高频延展更亮，久听不累",
            EqPresetKind::Meeting => "最强齿音控制，语音聚焦，强调可懂度",
        }
    }

    pub fn tooltip_text(self) -> &'static str {
        match self {
            EqPresetKind::Broadcast => "播音级：80/180 提升厚度，3.5k 与 8k 提升清晰与空气，450Hz 动态去浑浊。",
            EqPresetKind::BroadcastSoft => "播音级（柔和）：高频/存在提升减半，低频更平衡，长时间聆听更舒适。",
            EqPresetKind::OpenOffice => "开放办公：100/200 提厚，450 压浑浊，3.5k/8k 提亮，强调隔离。",
            EqPresetKind::ConferenceHall => "会议室去混响：80/180 提基座，350 强切驻波，8k 提空气，模拟近讲。",
            EqPresetKind::GeneralVoice => "通用语音增强：平衡的参数，适合大多数场景。",
            EqPresetKind::Podcast => "播客优化：更强齿音控制(5.5:1)，高频更亮，长时间收听也不累。",
            EqPresetKind::Meeting => "会议清晰化：最强齿音控制(5.8:1)，语音更聚焦。",
        }
    }
}

impl Default for EqPresetKind {
    fn default() -> Self {
        Self::Broadcast
    }
}

impl std::fmt::Display for EqPresetKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.display_name())
    }
}

const GENERAL_VOICE: EqPreset = EqPreset {
    name: "通用语音增强",
    default_mix: 0.55,
    bands: [
        BandSettings {
            label: "低频清理",
            frequency_hz: 100.0,
            q: 0.75,
            detector_q: 0.6,
            threshold_db: -35.0,
            ratio: 4.0,
            max_gain_db: 12.0,
            attack_ms: 30.0,
            release_ms: 220.0,
            mode: BandMode::Downward,
            filter: FilterKind::LowShelf,
            makeup_db: 0.0,
            static_gain_db: -0.5,
        },
        BandSettings {
            label: "浑浊控制",
            frequency_hz: 260.0,
            q: 1.2,
            detector_q: 1.0,
            threshold_db: -30.0,
            ratio: 3.0,
            max_gain_db: 8.0,
            attack_ms: 35.0,
            release_ms: 200.0,
            mode: BandMode::Downward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: -0.5,
        },
        BandSettings {
            label: "清晰增强",
            frequency_hz: 3100.0,
            q: 1.1,
            detector_q: 1.2,
            threshold_db: -33.0,
            ratio: 2.0,
            max_gain_db: 4.5,
            attack_ms: 20.0,
            release_ms: 80.0,
            mode: BandMode::Upward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: 0.8,
        },
        BandSettings {
            label: "齿音控制",
            frequency_hz: 7000.0,
            q: 2.0,
            detector_q: 2.0,
            threshold_db: -25.0,
            ratio: 5.0,
            max_gain_db: 10.0,
            attack_ms: 8.0,
            release_ms: 140.0,
            mode: BandMode::Downward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: -1.0,
        },
        BandSettings {
            label: "空气感",
            frequency_hz: 12000.0,
            q: 0.8,
            detector_q: 0.8,
            threshold_db: -38.0,
            ratio: 1.5,
            max_gain_db: 3.5,
            attack_ms: 40.0,
            release_ms: 250.0,
            mode: BandMode::Upward,
            filter: FilterKind::HighShelf,
            makeup_db: 0.0,
            static_gain_db: 0.5,
        },
    ],
};

const BROADCAST: EqPreset = EqPreset {
    name: "播音级",
    default_mix: 0.7,
    bands: [
        BandSettings {
            label: "低频基座",
            frequency_hz: 80.0,
            q: 0.7,
            detector_q: 0.7,
            threshold_db: -60.0,
            ratio: 1.0,
            max_gain_db: 6.0,
            attack_ms: 30.0,
            release_ms: 200.0,
            mode: BandMode::Upward,
            filter: FilterKind::LowShelf,
            makeup_db: 0.0,
            static_gain_db: 2.0,
        },
        BandSettings {
            label: "胸腔共鸣",
            frequency_hz: 180.0,
            q: 1.0,
            detector_q: 1.0,
            threshold_db: -60.0,
            ratio: 1.0,
            max_gain_db: 6.0,
            attack_ms: 30.0,
            release_ms: 200.0,
            mode: BandMode::Upward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: 3.0,
        },
        BandSettings {
            label: "浑浊控制",
            frequency_hz: 450.0,
            q: 1.5,
            detector_q: 1.5,
            threshold_db: -28.0,
            ratio: 3.0,
            max_gain_db: 4.0,
            attack_ms: 25.0,
            release_ms: 200.0,
            mode: BandMode::Downward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: 0.0,
        },
        BandSettings {
            label: "清晰增强",
            frequency_hz: 3500.0,
            q: 1.2,
            detector_q: 1.2,
            threshold_db: -60.0,
            ratio: 1.0,
            max_gain_db: 6.0,
            attack_ms: 20.0,
            release_ms: 160.0,
            mode: BandMode::Upward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: 2.0,
        },
        BandSettings {
            label: "空气感",
            frequency_hz: 8000.0,
            q: 0.7,
            detector_q: 0.7,
            threshold_db: -60.0,
            ratio: 1.0,
            max_gain_db: 8.0,
            attack_ms: 35.0,
            release_ms: 220.0,
            mode: BandMode::Upward,
            filter: FilterKind::HighShelf,
            makeup_db: 0.0,
            static_gain_db: 4.5,
        },
    ],
};

const BROADCAST_SOFT: EqPreset = EqPreset {
    name: "播音级（柔和）",
    default_mix: 0.75,
    bands: [
        BandSettings {
            label: "低频基座",
            frequency_hz: 90.0,
            q: 0.8,
            detector_q: 0.7,
            threshold_db: -40.0,
            ratio: 1.0,
            max_gain_db: 4.0,
            attack_ms: 30.0,
            release_ms: 220.0,
            mode: BandMode::Upward,
            filter: FilterKind::LowShelf,
            makeup_db: 0.0,
            static_gain_db: 2.5,
        },
        BandSettings {
            label: "胸腔",
            frequency_hz: 180.0,
            q: 1.0,
            detector_q: 1.0,
            threshold_db: -40.0,
            ratio: 1.0,
            max_gain_db: 4.0,
            attack_ms: 30.0,
            release_ms: 220.0,
            mode: BandMode::Upward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: 2.0,
        },
        BandSettings {
            label: "去浑浊",
            frequency_hz: 450.0,
            q: 1.5,
            detector_q: 1.5,
            threshold_db: -24.0,
            ratio: 2.0,
            max_gain_db: 3.5,
            attack_ms: 25.0,
            release_ms: 200.0,
            mode: BandMode::Downward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: -0.5,
        },
        BandSettings {
            label: "清晰",
            frequency_hz: 3200.0,
            q: 1.2,
            detector_q: 1.2,
            threshold_db: -32.0,
            ratio: 1.1,
            max_gain_db: 3.5,
            attack_ms: 25.0,
            release_ms: 160.0,
            mode: BandMode::Upward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: 0.5,
        },
        BandSettings {
            label: "空气",
            frequency_hz: 8000.0,
            q: 0.9,
            detector_q: 0.9,
            threshold_db: -33.0,
            ratio: 1.1,
            max_gain_db: 4.5,
            attack_ms: 35.0,
            release_ms: 220.0,
            mode: BandMode::Upward,
            filter: FilterKind::HighShelf,
            makeup_db: 0.0,
            static_gain_db: 1.0,
        },
    ],
};

const OPEN_OFFICE: EqPreset = EqPreset {
    name: "开放办公区",
    default_mix: 1.0,
    bands: [
        BandSettings {
            label: "低频基座",
            frequency_hz: 100.0,
            q: 0.7,
            detector_q: 0.7,
            threshold_db: -50.0,
            ratio: 1.0,
            max_gain_db: 6.0,
            attack_ms: 25.0,
            release_ms: 150.0,
            mode: BandMode::Upward,
            filter: FilterKind::LowShelf,
            makeup_db: 0.0,
            static_gain_db: 0.0,
        },
        BandSettings {
            label: "胸腔",
            frequency_hz: 200.0,
            q: 1.0,
            detector_q: 1.0,
            threshold_db: -50.0,
            ratio: 1.0,
            max_gain_db: 6.0,
            attack_ms: 25.0,
            release_ms: 150.0,
            mode: BandMode::Upward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: 2.0,
        },
        BandSettings {
            label: "去浑浊",
            frequency_hz: 450.0,
            q: 1.5,
            detector_q: 1.5,
            threshold_db: -30.0,
            ratio: 3.0,
            max_gain_db: 6.0,
            attack_ms: 25.0,
            release_ms: 200.0,
            mode: BandMode::Downward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: -4.0,
        },
        BandSettings {
            label: "清晰",
            frequency_hz: 3500.0,
            q: 1.2,
            detector_q: 1.2,
            threshold_db: -40.0,
            ratio: 1.5,
            max_gain_db: 6.0,
            attack_ms: 20.0,
            release_ms: 160.0,
            mode: BandMode::Upward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: 3.0,
        },
        BandSettings {
            label: "空气",
            frequency_hz: 8000.0,
            q: 0.9,
            detector_q: 0.9,
            threshold_db: -35.0,
            ratio: 1.5,
            max_gain_db: 6.0,
            attack_ms: 30.0,
            release_ms: 200.0,
            mode: BandMode::Upward,
            filter: FilterKind::HighShelf,
            makeup_db: 0.0,
            static_gain_db: 3.0,
        },
    ],
};

const CONFERENCE_HALL: EqPreset = EqPreset {
    name: "会议室去混响",
    default_mix: 0.85,
    bands: [
        BandSettings {
            label: "低频基座",
            frequency_hz: 80.0,
            q: 0.7,
            detector_q: 0.7,
            threshold_db: -50.0,
            ratio: 1.0,
            max_gain_db: 6.0,
            attack_ms: 30.0,
            release_ms: 220.0,
            mode: BandMode::Upward,
            filter: FilterKind::LowShelf,
            makeup_db: 0.0,
            static_gain_db: 1.5,
        },
        BandSettings {
            label: "胸腔",
            frequency_hz: 180.0,
            q: 1.0,
            detector_q: 1.0,
            threshold_db: -50.0,
            ratio: 1.0,
            max_gain_db: 6.0,
            attack_ms: 30.0,
            release_ms: 220.0,
            mode: BandMode::Upward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: 3.5,
        },
        BandSettings {
            label: "驻波削减",
            frequency_hz: 350.0,
            q: 1.4,
            detector_q: 1.4,
            threshold_db: -28.0,
            ratio: 3.0,
            max_gain_db: 8.0,
            attack_ms: 25.0,
            release_ms: 220.0,
            mode: BandMode::Downward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: -5.0,
        },
        BandSettings {
            label: "清晰",
            frequency_hz: 3500.0,
            q: 1.2,
            detector_q: 1.2,
            threshold_db: -40.0,
            ratio: 1.5,
            max_gain_db: 6.0,
            attack_ms: 20.0,
            release_ms: 160.0,
            mode: BandMode::Upward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: 1.5,
        },
        BandSettings {
            label: "空气",
            frequency_hz: 8000.0,
            q: 0.8,
            detector_q: 0.8,
            threshold_db: -35.0,
            ratio: 1.5,
            max_gain_db: 8.0,
            attack_ms: 35.0,
            release_ms: 240.0,
            mode: BandMode::Upward,
            filter: FilterKind::HighShelf,
            makeup_db: 0.0,
            static_gain_db: 5.0,
        },
    ],
};

const PODCAST: EqPreset = EqPreset {
    name: "播客优化",
    default_mix: 0.6,
    bands: [
        BandSettings {
            label: "低频收紧",
            frequency_hz: 90.0,
            q: 0.7,
            detector_q: 0.6,
            threshold_db: -36.0,
            ratio: 3.5,
            max_gain_db: 10.0,
            attack_ms: 28.0,
            release_ms: 240.0,
            mode: BandMode::Downward,
            filter: FilterKind::LowShelf,
            makeup_db: 0.0,
            static_gain_db: -0.8,
        },
        BandSettings {
            label: "箱音抑制",
            frequency_hz: 240.0,
            q: 1.1,
            detector_q: 1.0,
            threshold_db: -32.0,
            ratio: 2.8,
            max_gain_db: 6.0,
            attack_ms: 30.0,
            release_ms: 180.0,
            mode: BandMode::Downward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: -0.8,
        },
        BandSettings {
            label: "辅音提亮",
            frequency_hz: 3200.0,
            q: 1.4,
            detector_q: 1.4,
            threshold_db: -34.0,
            ratio: 2.3,
            max_gain_db: 5.0,
            attack_ms: 15.0,
            release_ms: 70.0,
            mode: BandMode::Upward,
            filter: FilterKind::Peak,
            makeup_db: 0.2,
            static_gain_db: 1.0,
        },
        BandSettings {
            label: "齿音守护",
            frequency_hz: 6800.0,
            q: 2.4,
            detector_q: 2.0,
            threshold_db: -24.0,
            ratio: 5.5,
            max_gain_db: 12.0,
            attack_ms: 6.0,
            release_ms: 160.0,
            mode: BandMode::Downward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: -1.5,
        },
        BandSettings {
            label: "空气延展",
            frequency_hz: 14000.0,
            q: 0.7,
            detector_q: 0.7,
            threshold_db: -36.0,
            ratio: 1.6,
            max_gain_db: 4.0,
            attack_ms: 35.0,
            release_ms: 260.0,
            mode: BandMode::Upward,
            filter: FilterKind::HighShelf,
            makeup_db: 0.1,
            static_gain_db: 0.8,
        },
    ],
};

const MEETING: EqPreset = EqPreset {
    name: "会议清晰化",
    default_mix: 0.5,
    bands: [
        BandSettings {
            label: "桌面噪声",
            frequency_hz: 110.0,
            q: 0.8,
            detector_q: 0.6,
            threshold_db: -34.0,
            ratio: 4.5,
            max_gain_db: 14.0,
            attack_ms: 32.0,
            release_ms: 260.0,
            mode: BandMode::Downward,
            filter: FilterKind::LowShelf,
            makeup_db: 0.0,
            static_gain_db: -2.0,
        },
        BandSettings {
            label: "低中降噪",
            frequency_hz: 230.0,
            q: 1.0,
            detector_q: 0.9,
            threshold_db: -31.0,
            ratio: 3.2,
            max_gain_db: 9.0,
            attack_ms: 32.0,
            release_ms: 210.0,
            mode: BandMode::Downward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: -1.0,
        },
        BandSettings {
            label: "语音聚焦",
            frequency_hz: 2700.0,
            q: 1.3,
            detector_q: 1.3,
            threshold_db: -30.0,
            ratio: 1.8,
            max_gain_db: 4.0,
            attack_ms: 18.0,
            release_ms: 90.0,
            mode: BandMode::Upward,
            filter: FilterKind::Peak,
            makeup_db: 0.1,
            static_gain_db: 0.5,
        },
        BandSettings {
            label: "齿音巡航",
            frequency_hz: 7200.0,
            q: 2.1,
            detector_q: 2.1,
            threshold_db: -23.0,
            ratio: 5.8,
            max_gain_db: 11.0,
            attack_ms: 5.0,
            release_ms: 150.0,
            mode: BandMode::Downward,
            filter: FilterKind::Peak,
            makeup_db: 0.0,
            static_gain_db: -2.0,
        },
        BandSettings {
            label: "空气补偿",
            frequency_hz: 11000.0,
            q: 0.9,
            detector_q: 0.9,
            threshold_db: -37.0,
            ratio: 1.4,
            max_gain_db: 3.5,
            attack_ms: 45.0,
            release_ms: 240.0,
            mode: BandMode::Upward,
            filter: FilterKind::HighShelf,
            makeup_db: 0.0,
            static_gain_db: 0.3,
        },
    ],
};
